#!/usr/bin/env python

# WIP
# - [x] take screenshot
# - [ ] self contained
# - [ ] login automatically credentials from Kubernetes Secrets (is this really needed?)

# TODO: put this in tools container or use Docker
# pip install selenium
# sudo pacman -S geckodriver

import time
from selenium import webdriver

apps = [
    {
        'name': 'home',
        'url': 'https://home.iuliandita.com'
    },
    {
        'name': 'gitea',
        'url': 'https://git.iuliandita.com/ops/homelab'
    },
    {
        'name': 'argocd',
        'url': 'https://argocd.iuliandita.com/applications/root'
    },
    {
        'name': 'vault',
        'url': 'https://vault.iuliandita.com/ui/vault/secrets'
    },
    {
        'name': 'tekton',
        'url': 'https://tekton.iuliandita.com/#/namespaces/tekton-pipelines/pipelineruns/homelab?pipelineTask=external&step=plan'
    },
    {
        'name': 'matrix',
        'url': 'https://chat.iuliandita.com/#/room/#random:matrix.iuliandita.com'
    },
    {
        'name': 'grafana',
        'url': 'https://grafana.iuliandita.com/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster'  # wtf is this ID
    },
]

options = webdriver.firefox.options.Options()
options.headless = True

driver = webdriver.Firefox(
    options=options,
    firefox_profile=webdriver.FirefoxProfile(  # TODO: deprecated
        profile_directory="/home/iuliandita/.mozilla/firefox/h05irklw.default-release"  # TODO: do not hard code
    )
)
driver.set_window_size(1920, 1080)

for app in apps:
    print(f"Opening {app['url']}")
    driver.get(app['url'])
    time.sleep(3)  # TODO: wait for full page load instead of sleep
    driver.save_screenshot(f"{app['name']}.png")
    print(f"Screenshot saved to {app['name']}.png")

driver.close()
